#!/bin/bash
if [ -n "$1" ]; then
echo copy here
cp -r /home/yasemin/eclipse-workspace/Hadoop21/piccolo/edu/nyu/cs/piccolo/* /home/yasemin/git-repo/piccolo/src
cp /home/yasemin/eclipse-workspace/Hadoop21/bash-files/* /home/yasemin/git-repo/piccolo/bin/
git add /home/yasemin/git-repo/piccolo/*
echo 'git commit -m' $1
git commit -m $1
echo git push origin master
git push origin master --force
else
echo "enter commit comment"
fi
